version: '3.8'

services:
  compass:
    build: .
    container_name: compass-app
    ports:
      - "5030:5030"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./json:/app/json
    environment:
      - FLASK_ENV=production
      - ROUTING_ENGINE_URL=https://router.project-osrm.org
    restart: unless-stopped
